version: '3.9'

services:
  mongo-server:
    image: mongo
    container_name: mongo-server
    volumes:
      - ./server.pem:/etc/ssl/mongo/server.pem
      - ./ca.crt:/etc/ssl/mongo/ca.crt
      - ./mongod.conf:/etc/mongod.conf
    command: ["mongod", "--config", "/etc/mongod.conf"]
    ports:
      - "27017:27017"